#Joseph Barton
#CPSC 1021-004, F16
#Lab 8
#jbarto3

Date: Date.cpp driver.cpp
			g++ -Wall Date.cpp driver.cpp -o Date

run:	Date
			./Date

clean:
			rm Date
			rm *.o
package:
			tar -cvzf lab8.tar.gz makefile Date.h Date.cpp driver.cpp
