#Joseph Barton
#CPSC 1021-004, F16
#Lab 11
#jbarto3

Sort: functions.cpp driver.cpp
			g++ -Wall functions.cpp driver.cpp -o Sort

run:	Sort input1.txt
			./Sort input1.txt

clean:
			rm Sort
			rm *.o
package:
			tar -cvzf jbarto3-lab12.tar.gz makefile functions.h functions.cpp driver.cpp
